from enum import Enum
from mimetypes import init
from typing import Literal

class SystemCanonical(str, Enum):
  AuthnSignatureService = "AuthnSignatureService"
  BasisConsumer = "BasisConsumer"
  CardTerminal = "CardTerminal"
  Connector = "Connector"
  ConnectorHighspeed = "ConnectorHighspeed"
  CVCRootECC = "CVCRootECC"
  Directory = "Directory"
  EGK = "EGK"
  EPrescriptionBackend = "EPrescriptionBackend"
  EPrescriptionPersonalFrontend = "EPrescriptionPersonalFrontend"
  EPrescriptionPrivacyFrontend = "EPrescriptionPrivacyFrontend"
  ExistingNetworksGateway = "ExistingNetworksGateway"
  FHIRDirectory = "FHIRDirectory"
  HealthInsuranceConsumer = "HealthInsuranceConsumer"
  HealthInsurancePrivacyFrontend = "HealthInsurancePrivacyFrontend"
  HBA = "HBA"
  IDPFederated = "IDPFederated"
  IDPFederationMaster = "IDPFederationMaster"
  IDPService = "IDPService"
  KIMBackend = "KIMBackend"
  KIMClientModule = "KIMClientModule"
  MobileCardTerminal = "MobileCardTerminal"
  NCPEH = "NCPEH"
  OCSPProxy = "OCSPProxy"
  PharmaciesDirectory = "PharmaciesDirectory"
  PHRBackend = "PHRBackend"
  PHRKeyGenerationService = "PHRKeyGenerationService"
  PHRPersonalFrontend = "PHRPersonalFrontend"
  PrivateKeyGenerator = "PrivateKeyGenerator"
  Repository = "Repository"
  SMCB = "SMCB"
  TIDNS = "TIDNS"
  TIMessengerBackend = "TIMessengerBackend"
  TIMessengerFrontend = "TIMessengerFrontend"
  TINetwork = "TINetwork"
  TINTP = "TINTP"
  TIRootCA = "TIRootCA"
  TSLService = "TSLService"
  TSP_CVC = "TSP_CVC"
  TSP_X509_nonQES_eGK = "TSP_X509_nonQES_eGK"
  TSP_X509_nonQES_HBA = "TSP_X509_nonQES_HBA"
  TSP_X509_nonQES_Komp = "TSP_X509_nonQES_Komp"
  TSP_X509_nonQES_SMCB = "TSP_X509_nonQES_SMCB"
  TSP_X509_QES = "TSP_X509_QES"
  VPNService = "VPNService"
  VSDM_CMS = "VSDM_CMS"
  VSDM_Intermediary = "VSDM_Intermediary"
  VSDM_UFS = "VSDM_UFS"
  VSDM_VSD = "VSDM_VSD"

  HealthProfessionalSoftware = "HealthProfessionalSoftware"
  InternetAccess = "InternetAccess"
  InternetServices = "InternetServices"