# yaml-language-server: $schema=https://raw.githubusercontent.com/spilikin/api-tools/main/schema/ApprovalObject.schema.json
apiVersion: v1
kind: ApprovalObject
meta:
  name: gemProdT_eRp_FD
  version: 1.2.0
spec:
  provides:
    - name: I_ERP_Task_Prescribe
    - name: I_ERP_Task_Dispense
  